language: python
python:
    - 2.6
    - 2.7
sudo: false
cache:
  directories:
    - eggs
install:
  - sed -ie "s#versions-$TRAVIS_PYTHON_VERSION.x#versions#" travis.cfg
  - pip install -r requirements.txt
  - buildout -c travis.cfg annotate
  - buildout -c travis.cfg -N -q
branches:
  only:
    - master
script:
  - bin/code-analysis
  - bin/test
